apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  - ../../base
  - kubeflow-training-roles.yaml
images:
  - name: kubeflow/training-operator
    newTag: "v1-855e096"
  # - name: kubeflow/training-operator
  #   newName: rajatonit/training-operator
  #   newTag: "760ac1171dd30039a7363ffa03c77454bd714da5"
