apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pvcviewrs-role
  namespace: kubeflow-user-example-com
rules:
- apiGroups: ["kubeflow.org"]
  resources: ["pvcviewers"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pvcviewrs-rolebinding
  namespace: kubeflow-user-example-com
subjects:
- kind: ServiceAccount
  name: volumes-web-app-service-account
  namespace: kubeflow
roleRef:
  kind: Role
  name: pvcviewrs-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user-role
  namespace: kubeflow-user-example-com
subjects:
- kind: User
  name: user@example.com
  namespace: kubeflow
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
